version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: python app.py

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    command: ["npx", "vite", "preview", "--host", "0.0.0.0", "--port", "4173"]
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      - backend
